### ISSUE TITLE
Binary Classification not working

### ISSUE THREAD

**Issue by SriRangaTarun** [ncullen93/torchsample#101]
Here's my code for training a binary classifier : 

    trainer.compile(loss='cross_entropy',
                optimizer='adadelta')

    trainer.fit(train_sequences[:np.int32(0.8*len(train_sequences))], train_targets[:np.int32(0.8*len(train_targets))],

    val_data=(train_sequences[np.int32(0.8*len(train_sequences)):], train_targets[np.int32(0.8*len(train_targets)):]),

            num_epoch=20, 
            batch_size=20,
            verbose=1)

[train_targets and val_sequences are 1-d binary lists]

It gives a RunTime error : 

**RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /opt/conda/conda-bld/pytorch-cpu_1532576596369/work/aten/src/THNN/generic/ClassNLLCriterion.c:93**

**Comment by qlwang25** [comment]
Obviously, the error message has already given the situation.
The cur_target must in [0, n_classes).
