### ISSUE TITLE
Index error in module_trainer.py

### ISSUE THREAD

**Issue by sagsshakya** [ncullen93/torchsample#117]
Getting an index error like this.

_IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number._

The line pointed is:  
_batch_logs['loss'] = loss.data[0]_

I tried using 
 _batch_logs['loss'] = loss.data_
AND
 _batch_logs['loss'] = loss.data.item()_

Didn't work!

**Comment by LittleRobertTables** [comment]
I have the same error, @sagsshakya did you manage to find the problem?

**Comment by sagsshakya** [comment]
No sir.
