### ISSUE TITLE
AttributeError: 'CNN' object has no attribute '_has_regularizers'

### ISSUE THREAD

**Issue by EelcovdW** [ncullen93/torchsample#13]
Hi! Looks like a great library, but I'm getting the following error on python 3.6, newest version of pytorch and this repo:

```Traceback (most recent call last):
  File "/home/eelco/PycharmProjects/pt_mnist/train_ps.py", line 51, in <module>
    train(20)
  File "/home/eelco/PycharmProjects/pt_mnist/train_ps.py", line 48, in train
    nb_epoch=n_epochs)
  File "/home/eelco/anaconda3/lib/python3.6/site-packages/torchsample/modules/module_trainer.py", line 444, in fit_loader
    callbacks.on_train_begin()
  File "/home/eelco/anaconda3/lib/python3.6/site-packages/torchsample/callbacks.py", line 67, in on_train_begin
    callback.on_train_begin(logs)
  File "/home/eelco/anaconda3/lib/python3.6/site-packages/torchsample/callbacks.py", line 170, in on_train_begin
    if self.model._has_regularizers:
  File "/home/eelco/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 238, in __getattr__
    type(self).__name__, name))
AttributeError: 'CNN' object has no attribute '_has_regularizers'
```

My code, where train_loader and test_loader are the same as in the pytorch mnist examples:
```py
    model = CNN((1, 28, 28))
    trainer = ModuleTrainer(model)

    trainer.compile(
        loss='nll_loss',
        optimizer='adam',
    )

    trainer.fit_loader(train_loader,
                       val_loader=test_loader,
                       nb_epoch=10)
```

Seems the History callback is looking for attributes in the Module that should be in ModuleTrainer?

Edit:
I saw Issue #7 reported the same bug, but when removing the History callback, training gives errors (`AttributeError: 'CNN' object has no attribute 'history'`)

**Comment by ncullen93** [comment]
Yes that's exactly what it is. this should be fixed now! Can you check and get back to me? Try the new example `mnist_loader_example` if yours doesn't work (but it should).

**Comment by EelcovdW** [comment]
Confirmed! It works, also with the DataLoader from pytorch.

**Comment by ncullen93** [comment]
I think you mean dataset from pytorch? There is no DataLoader in torchsample, but there is a separate, much improved TensorDataset and FolderDataset. Anyways glad to hear :) closing but plz let me know if you have any other bugs or feature requests in a separate issue

**Comment by ncullen93** [comment]
I think you mean dataset from pytorch? There is no DataLoader in torchsample, but there is a separate, much improved TensorDataset and FolderDataset. Anyways glad to hear :) closing but plz let me know if you have any other bugs or feature requests in a separate issue

**Comment by EelcovdW** [comment]
Yes the dataset from pytorch, just the same as their examples. Ill have a look at the new and improved ones!

**Comment by ncullen93** [comment]
THe ones in torchsample support input transforms, target transforms , and co-transforms (eg when both input and target images are images and you have to do the same crop).
