### ISSUE TITLE
[feature request] Brighting/Color/Lighting transformations (data augmentations)? 

### ISSUE THREAD

**Issue by wangg12** [ncullen93/torchsample#16]
Is there any plan to add more data augmentations? 
Such as color jittering, lighting or brightness in 
https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua

**Comment by ncullen93** [comment]
Yes!!! Wow I am actually just working on this today. Was planning to do something like [tensorflow's stuff](https://www.tensorflow.org/api_docs/python/tf/image) but I'll check that out. Expect some color/lighting/brightning-based transforms by Monday. Let me know if there are any specific ones you want

**Comment by wangg12** [comment]
@ncullen93 Good to know this!

**Comment by ncullen93** [comment]
This is done check transforms/image_transforms.py
