### ISSUE TITLE
Integrate torchsample with DataLoader

### ISSUE THREAD

**Issue by trypag** [ncullen93/torchsample#2]
Hi,
This project fills the gap for data augmentation and sampling, however I am a bit confused about how to integrate it with `DataLoader`, I really liked the fact that multiple workers where taking care of building the batches. If I understand correctly your datasets are complete substitutes to a `DataLoader` right ?
Thanks

**Comment by trypag** [comment]
Is the code for building batches inspired from `DataLoader` ?

**Comment by ncullen93** [comment]
Yes it's the same exact code.. I just remove the need for the DataLoader by Creating it automatically when you iterate through the data. I realize that's kind of confusing and may let people optionally use DataLoader .

**Comment by ncullen93** [comment]
It should have the same exact speed as the official code

**Comment by trypag** [comment]
Ok thanks
