### ISSUE TITLE
ReduceLROnPlateau Patience

### ISSUE THREAD

**Issue by fizzxed** [ncullen93/torchsample#23]
The patience argument in the ReduceLROnPlateau callback seems to not do anything.
Indeed, if we see, patience is only used in assigning a class variable, self.patience, which is never used in on_epoch_end.
Also shouldn't https://github.com/ncullen93/torchsample/blob/master/torchsample/callbacks.py#L508
be changed to
```python
elif self.monitor_op(current_loss, self.best_loss):
```

**Comment by ncullen93** [comment]
you're correct about the patience. Thanks! There should not be an `elif` instead of an `if` because the wait gets reset and the best loss gets saved regardless of whether you're in the cooldown phase. This is basically a line-by-line port of the Keras version, which does it that way.

**Comment by fizzxed** [comment]
I see, that makes sense. I was going off the old comments I guess!
