### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by cjmcmurtrie** [ncullen93/torchsample#28]
Great library, love it!

Some of the tools are not Python 2 compatible. For instance `RandomChoiceRotate` (and anything that uses `util.th_random_choice`) does not work because in Python 2 the `round` method returns a float, not an integer, and the below `torch.zeros` throws an exception.

```
idx_vec = th.cat([th.zeros(round(p[i]*1000))+i for i in range(len(p))])
```

I can make a pull request to try to fix it if you like. I would advise running tests on both Python 2 and 3 compilers.

**Comment by ncullen93** [comment]
Thanks! yes good advice. If you have any PRs I'd definitely appreciate it. Otherwise I'll try to fix`th_random_choice` and go from there.
