### ISSUE TITLE
cannot import name th_meshgrid

### ISSUE THREAD

**Issue by srv902** [ncullen93/torchsample#3]
Hi there,

There is an import error for 

> th_meshgrid

 whenever I try to import torchsample. In utils.py I can only find _th_meshgrid2d_ and _th_meshgrid3d_.

**Comment by ncullen93** [comment]
Yeah I renamed it because I added a 3D affine transform + tri linear interpolation.. Ill fix that in a sec thanks for letting me know

**Comment by srv902** [comment]
@ncullen93 Yeah, it's working now.
