### ISSUE TITLE
module_trainer: Make all non-training Variables volatile

### ISSUE THREAD

**Issue by Mctigger** [ncullen93/torchsample#31]
Hi, I use Pytorch and your great framework for two days and I observed high VRAM usage while evaluating my models. I think this is caused by not using volatile variables in [module_trainer.py](https://github.com/ncullen93/torchsample/blob/master/torchsample/modules/module_trainer.py#L867) for tasks which are not related to training. 
When I change `Variable(...)` to `Variable(...,volatile=True)`  memory consumption is like I'd expect.

**Comment by ncullen93** [comment]
implemented thank you :) let me know if it's better
