### ISSUE TITLE
Error when some layers are frozen

### ISSUE THREAD

**Issue by arunpatala** [ncullen93/torchsample#46]
When I am trying to finetune a pretrained network, I am freezing some layers params using require_grad=False. The optimizer is trying to optimize all params causing 
ValueError: optimizing a parameter that doesn't require gradients. Is there are a way to only pass params that have require_grad as True.
Thanks

**Comment by arunpatala** [comment]
I set the arg optimizer_parameters=model.fc.parameters() in trainer.compile.
But i guess it is being passed to optimizer initialization:

line 133, in set_optimizer
TypeError: __init__() got an unexpected keyword argument 'parameters'

**Comment by arunpatala** [comment]
added kwargs.pop('parameters',None) after line 128

**Comment by ncullen93** [comment]
Oh I see. Wait can you tell me where in this function you added that line (i'd appreciate it):

```python
    def set_optimizer(self, optimizer, **kwargs):
        if type(optimizer) is type or isinstance(optimizer, str):
            if 'parameters' in kwargs:
                parameters = kwargs['parameters']
            else:
                parameters = self.model.parameters()

            optimizer = _validate_optimizer_input(optimizer)
            self._optimizer = optimizer(parameters, **kwargs)
        else:
            self._optimizer = optimizer
```

**Comment by recastrodiaz** [comment]
I guess there is a better way, but the following works for me:
``` PYTHON
# 1. Set some layers of the model to be non-trainable (param.requires_grad = False)
# 2. Monkey patch the instance parameters() method to return trainable weights only
import types

def parameters(self):
    p = filter(lambda p: p.requires_grad, nn.Module.parameters(self))
    return p

model.parameters = types.MethodType(parameters, model)

# 3. Profit
trainer.fit_loader(train_loader, val_loader=val_loader, nb_epoch=1)
```

**Comment by arunpatala** [comment]
def set_optimizer(self, optimizer, **kwargs):
        if type(optimizer) is type or isinstance(optimizer, str):
            if 'parameters' in kwargs:
                parameters = kwargs['parameters']
                kwargs.pop('parameters',None)
