### ISSUE TITLE
Train and validation data assumed same size?

### ISSUE THREAD

**Issue by plumdeq** [ncullen93/torchsample#49]
Assuming train/validation data sets are 80% and 20% of the whole dataset, respectively.

When I run

```python
trainer.fit(X_train, y_train, 
            val_data=(X_test, y_test),
            num_epoch=20,
            batch_size=128,
            verbose=1)
``` 

I get

```python
home/xxx/torchsample/torchsample/modules/module_trainer.py in fit(self, inputs, targets, val_data, num_epoch, batch_size, shuffle, cuda_device, verbose)
    211             num_val_inputs, num_val_targets = _parse_num_inputs_and_targets(val_data[0], val_data[1])
    212             if (num_inputs != num_val_inputs) or (num_targets != num_val_targets):
--> 213                 raise ValueError('num_inputs != num_val_inputs or num_targets != num_val_targets')
    214             val_inputs, val_targets = val_data
    215         has_val_data = val_data is not None

ValueError: num_inputs != num_val_inputs or num_targets != num_val_targets
```

Train and validation data sets should have the same sizes? O_o

**Comment by ncullen93** [comment]
The issue is not the number of samples, but the shapes and counts of the inputs/targets to the network. I'll make that more clear. At least that's what it's supposed to be unless there's a bug

**Comment by plumdeq** [comment]
Sorry to reply only now, yes, indeed, the problem was the incompatible shapes of the tensors (this is why I closed the issue). Also, using the latest cloned version helps.

**Comment by plumdeq** [comment]
By the way, I think you could add ["Pillow", "tqdm", "nibabel"] in the list of dependencies.

**Comment by vfdev-5** [comment]
> By the way, I think you could add ["Pillow", "tqdm", "nibabel"] in the list of dependencies.

I agree with at least `Pillow` and `tqdm`, but `nibabel` is very specific.
