### ISSUE TITLE
Error when install torchsample

### ISSUE THREAD

**Issue by magicwyzh** [ncullen93/torchsample#50]
Hi, when i want to install torchsample by "python setup.py install", I meet synteaxError as below:
 File "build/bdist.linux-x86_64/egg/torchsample/datasets.py", line 106
    inputs = np.empty((len(load_range), *_parse_shape(input_sample)))
                                        ^
SyntaxError: invalid syntax

I am not familiar with Python, I guess it is because my python version does not support this syntax or there are some other problems remained under cover.... 
May be it is a naive problem, but please give me a helping hand.

**Comment by magicwyzh** [comment]
Thanks a lot!

**Comment by ncullen93** [comment]
yeah almost certainly your python version. I fixed it.. should work now regardless. thanks
