### ISSUE TITLE
predict() and predict_loader() are not using the GPU

### ISSUE THREAD

**Issue by recastrodiaz** [ncullen93/torchsample#53]
The latest v0.1.3  version is not sending the input(s) and target(s) to GPU() before the forward pass: https://github.com/recastrodiaz/torchsample/commit/19e80210868632597e14ba400b4ff72ac17e5697#diff-f659837420f2b751abd33ab404195ce8R423

**Comment by antorsae** [comment]
What's the best way to do this?
