### ISSUE TITLE
Use command [python set_up.py install --user] to install torchsample but Failed 

### ISSUE THREAD

**Issue by qii67** [ncullen93/torchsample#54]
I want to use torchsample to do transforms on my datassets, but i don't have the su access to run [python set_up.py install]. After google it, I run [python set_up.py install --user] to install torchsample. But an error occurs to me, which is [File "build/bdist.linux-x86_64/egg/torchsample/datasets.py", line 106
    inputs = np.empty((len(load_range), *_parse_shape(input_sample)))
                                        ^
SyntaxError: invalid syntax]. 
when i finish installing torchsample, I try to use [from torchsample.transforms import Affine] to apply affine to my dataset , but appears [Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/torchsample/__init__.py", line 6, in <module>
  File "/home/guest1/.local/lib/python2.7/site-packages/torchsample-0.1.3-py2.7.egg/torchsample/datasets.py", line 106
    inputs = np.empty((len(load_range), *_parse_shape(input_sample)))
                                        ^
SyntaxError: invalid syntax]

I am totally a newbie to pytorch and i don't know how to solve that now TT

**Comment by ncullen93** [comment]
it's a python 2.7 issue. you have to upgrade to python 3.x

**Comment by qii67** [comment]
Thanks a lot, it works!  I download the release version which is not the latest , maybe it should be updated >o<
