### ISSUE TITLE
trainer does not work with  FolderDataset

### ISSUE THREAD

**Issue by A-Jacobson** [ncullen93/torchsample#61]
```AttributeError: 'FolderDataset' object has no attribute 'num_inputs'```
when attempting to call `fit_loader` using an FolderDataset dataset.

Same problem with the default torch ImageFolder dataset

**Comment by arnokha** [comment]
I got the same error.

Seems like it was introduced [here](https://github.com/ncullen93/torchsample/commit/ef2be6e6d06e153141acdbd44e54405fe1dc2c4a#diff-f659837420f2b751abd33ab404195ce8).

If you need a work around for now you can just install the [previous version](https://github.com/ncullen93/torchsample/commit/b7ef2f56800ede55cb1206b2070baddb17955a9d#diff-f659837420f2b751abd33ab404195ce8)
