### ISSUE TITLE
AttributeError: 'CIFAR10' object has no attribute 'num_inputs'

### ISSUE THREAD

**Issue by pbloem** [ncullen93/torchsample#65]
I get this error when I load CIFAR10 (as described in [the pytorch 60 min tutorial](http://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#what-about-data)) and try to fit a simple ConvNet with trainer.fit_loader(). It looks like fit_loader calls some attribute that is not or no longer part of the dataset object (at least for CIFAR 10).

This used to work, but it stopped working after I updated both pytorch (version 0.2.0.post3
) and torchsample (version 0.1.3) recently.

Here is a simple(ish) example:
https://gist.github.com/pbloem/d370634327cccccf4c56bb6bb7d411f5

**Comment by phizaz** [comment]
+1 happened to me as well.

**Comment by arunpatala** [comment]
I have faced a similar problem. I think this is because of new features supporting multiple inputs and targets. I have written a wrapper class that converts pytorch dataset to torchsample dataset, hope it helps you.


class WrapperDataset(BaseDataset):

    def __init__(self, dataset):
        self.dataset = dataset
        self.num_inputs = 1
        self.num_targets = 1
        
    def __getitem__(self, index):
        return self.dataset.__getitem__(index)
    
    def __len__(self):
            return self.dataset.__len__()

**Comment by Abhishaike** [comment]
@arunpatala: Can you give an example on how to use this class? What is 'BaseDataset'?
