### ISSUE TITLE
[feature request] ModuleTrainer class 

### ISSUE THREAD

**Issue by ncullen93** [ncullen93/torchsample#7]
Could potentially add a `ModuleTrainer` or `ModelTrainer` class that works similarly to `SuperModule` but can take in one or more normal `nn.Module` classes.. This would allow for support of pre-trained networks and more flexible training structures, while also allowing seamless integration with all other pytorch code

@recastrodiaz

**Comment by recastrodiaz** [comment]
Sounds like a great idea! ;)
I'll get back to you with some questions Monday or sooner if possible.

**Comment by ncullen93** [comment]
check out what I just put in `modules/model_trainer.py` . Add initializations as well.

**Comment by recastrodiaz** [comment]
Amazing! This is definitely what I had in mind! I saw that you added support for multiple forwards inputs*. That's something I was really looking for!

The History callback class seems to be looking for non existing attributes in the model. Maybe the History constructor should accept a ModuleTrainer as init parameter? (Although this sounds like a circular dependency...). I've removed it from the callbacks from now in ModuleTrainer `__init__` function:

```Python
self._callbacks = [self.history]

#-->

self._callbacks = []
```

``` LOG
History class:
/Users/rodrigo/Libs/torchsample/torchsample/callbacks.py in on_train_begin(self, logs)
    168     def on_train_begin(self, logs=None):
    169         self.losses = []
--> 170         if self.model._has_regularizers:
    171             self.regularizer_losses = []
    172         if self.model._has_lagrangian_constraints:
```

Thanks again for the excellent work!

**Comment by ncullen93** [comment]
should be fixed can you check?

**Comment by ncullen93** [comment]
closed bc ModuleTrainer was added

**Comment by recastrodiaz** [comment]
Can confirm ModuleTrainer works!
