### ISSUE TITLE
How to properly call RandomChoice*

### ISSUE THREAD

**Issue by lpuglia** [ncullen93/torchsample#76]
I just noticed that to properly call functions of the form:

> RandomChoice*

you have to input a Tensor as first argument, e.g.:

`RandomChoiceBrightness(values=torch.FloatTensor([-0.5,0.0,0.5]),p=[0.1,0.8,0.1])`

is this the intended behaviour? Using a list (as it is mentioned in the comment of the code) you get:

```
/opt/miniconda2/envs/mypython3/lib/python3.6/site-packages/torchsample/utils.py in th_random_choice(a, n_samples, replace, p)
    398         idx = (th.floor(th.rand(n_samples)*999)).long()
    399         idx = idx_vec[idx].long()
--> 400     selection = a[idx]
    401     if n_samples == 1:
    402         selection = selection[0]

TypeError: list indices must be integers or slices, not torch.LongTensor
```

**Comment by kkorovesis** [comment]
Same problem here.
