### ISSUE TITLE
Getting the error of ModuleTrainer having no attribute history

### ISSUE THREAD

**Issue by chinmay5** [ncullen93/torchsample#83]
When trying to run

    trainer.set_callbacks([
        callbacks.ModelCheckpoint(
            paths.models,
            name,
            save_best_only=False,
            saving_strategy=lambda epoch: True
        ),
        CSVLogger('./logs/' + name),
        LRScheduler(schedule)
    ])

I get the error:-

File "/home/chinmay/PycharmProjects/test-sample/venv/src/torchsample/torchsample/modules/module_trainer.py", line 103, in set_callbacks

    self._callbacks = [self.history] + callbacks
AttributeError: 'ModuleTrainer' object has no attribute 'history'

Please let me know what exactly am I doing wrong here

**Comment by neuronphysics** [comment]
Hi I am getting the same error:
```
  self.trainer.set_callbacks(callbacks)
  File "/ssd003/home/src/torchsample/torchsample/modules/module_trainer.py", line 103, in set_callbacks
    self._callbacks = [self.history] + callbacks
AttributeError: 'ModuleTrainer' object has no attribute 'history'
```
How can I get history of `loss` and `metric` values?
