### ISSUE TITLE
how to install torchsample?

### ISSUE THREAD

**Issue by hurricane2018** [ncullen93/torchsample#93]
Thank you for your wonderful work. But how to install torchsample ?

**Comment by cy69855522** [comment]
!pip install git+https://github.com/ncullen93/torchsample

**Comment by qiuhuaqi** [comment]
How to make sure all torchsample dependancies are installed? I had to manually pip install every missing dependancy complained by the import call.

**Comment by hh10** [comment]
pip install -e git+https://github.com/ncullen93/torchsample.git#egg=torchsample
worked as is for me.

**Comment by CharFran72** [comment]
Just great. Wonderful job!!!!!!
